### ISSUE TITLE
Desync after enabling altert

### ISSUE THREAD

**Issue by MalthusEx** [IshFx/spawner-alert#2]
All players in multiplayer will be desyncronized after one of the players activates the alert.

Map version: 1.0.0
Mod: 0.1.2

**Comment by ishfx** [comment]
I haven't had the chance to test the mod in MP environment yet. Will do as soon as i can.

In the mean time, can you maybe provide more information. 
- Does desyncronization happen instantly at mod activation ? 
- Are spawners consuming pollution ?

Thanks !

**Comment by MalthusEx** [comment]
Does desyncronization happen instantly at mod activation: yes

It seems to happen only once in a while for each player. After rejoining again, the mod can be activeted without desync for the same player. If another one activates it, desync happens again.

It also seems to happen only when other players are logged in to the server.

Not sure about the spawners consuming pollution at the moment when desync happens. But once the mod is activated, it works really well. But it has to be activated each time joining the server.

**Comment by ishfx** [comment]
Alright, thanks for the clarifications!
I think i know where the bug comes from.

It will be fixed in the next release.

**Comment by ishfx** [comment]
Should be fixed in cc89588a7e3ba63aa26fa94405f2c4ee2a5b7f63 (v 0.1.3).
@MalthusEx I couldn't test the fix in MP, can you tell me if you don't encounter the bug anymore ?
