### ISSUE TITLE
Mod crash - (0.1.5)

### ISSUE THREAD

**Issue by MrWashingToad** [IshFx/spawner-alert#4]
The mod Spawner alert (0.1.5) caused a non-recoverable error.
Please report this to mod author.

Error while running spawner-alert::on_nth_tick(60)
_ _spawner-alert_ _/control.lua:74: attempt to index field '?' ( a nil value)
stack traceback:
_ _spawner-alert_ _/control.lua:74: in function
<_ _spawner-alert_ _/control.lua:54>
![factorio spawner alert 0 1 5 mod crash report](https://user-images.githubusercontent.com/15614249/94170202-c2b0c600-fe5d-11ea-94fa-542ada24d86f.JPG)

**Comment by ishfx** [comment]
Hi,

Can you please give more insights about the error ?
When does the crash happen ? Can you provide a save so i can reproduce it locally ?

Thanks!

**Comment by MrWashingToad** [comment]
Sure - auto save attached. As soon as pollution ticks over to the biter base near spawn to the West, it crashes.
[_autosave3.zip](https://github.com/IshFx/spawner-alert/files/5277745/_autosave3.zip)

**Comment by ishfx** [comment]
Huum, that's weird, it didn't crash for me when i ran your save.
![image](https://user-images.githubusercontent.com/23222270/94186228-b7ce5380-fea6-11ea-8319-54ac77c2ad9c.png)

Are you playing on a MP server ?

**Comment by MrWashingToad** [comment]
I loaded save, immediately removed the burner miners and reduced pollution. This allowed another 30-40 min of play. But as soon as I generate pollution to hit that biter spawner, it crashes: (Just now; new autosave 
[_autosave1.zip](https://github.com/IshFx/spawner-alert/files/5278715/_autosave1.zip)
attached)
![image](https://user-images.githubusercontent.com/15614249/94191330-5b097380-fe7b-11ea-8d88-15030ff001de.png)

**Comment by ishfx** [comment]
Can you try to disable then enable the alerts with **SHIFT + i** ?

**Comment by MrWashingToad** [comment]
Seems to be working after disable and re-enable of alerts - I'll keep puttering around and see if I can get more info on what exactly it's issue is. 
I went thru an entire 70+ hour campaign on a railworld map to launching a rocket and had no issues whatsoever with it, started this deathworld, and as soon as pollution was eaten by biter spawner, it would fatal crash.
![coding it doesn't work why it works why](https://user-images.githubusercontent.com/15614249/94271238-55f60400-ff0f-11ea-8f70-bf4136dc7f22.jpg)

**Comment by ishfx** [comment]
Normally it shouldn't happen anymore. Disabling/enabling the alerts resets the internal state.
I think i know why you had the crash the first time, its the combination of several (rare) factors.

Anyway, keep me posted if the mod crashes again. I'll keep this issue open.

**Comment by MrWashingToad** [comment]
Once I reset it, had no further issues, got it to where I could see the alerts. Will have to try on another world this one was unsustainable (I screwed up! :D)  Great mod though, has saved me several times.

**Comment by MrWashingToad** [comment]
New world; same thing- as soon as pollution ticked the biter-spawner, crashed. Reloaded auto-save, immediately hit Shift + i, and toggled off and on, and no problems since. 
Maybe have a help window come up to show people "this is how you use it" and have them auto-toggle on/off, or set it to do that on first load?

**Comment by ishfx** [comment]
Alright, thanks for the additional information.
The mod shouldn't crash in the first place, so adding a help window isn't an actual fix.

The bug will be fixed in the next release!

**Comment by ishfx** [comment]
Should be fixed in 201a922e92fe28afdf2ead9342c262f089ad5aad (v0.1.6).
